blank_issues_enabled: true
contact_links:
  - name: Get help
    url: https://huddlebot.vercel.app/
    about: For help with HuddleBot contact support at [support@huddlebot.vercel.app](mailto:support@huddlebot.vercel.app).
  - name: Report a vulnerability
    url: https://huddlebot.vercel.app/
    about: Please see the [Vulnerability Disclosure Policy](support@huddlebot.vercel.app) and report any vulnerabilities using support@huddlebot.vercel.app.
